blank_issues_enabled: true
contact_links:
  - name: Blank issue
    url: https://github.com/Piero24/TelegramBot-AmazonOffers/issues/new
    about: Use this blank template only if the prevoius templates do not apply to your issue or question.
