blank_issues_enabled: true
# contact_links:
#   - name: Blank issue
#     url: https://discord.gg/5CceB5Y6Zt
#     about: Use this blank template only if the prevoius templates do not apply to your issue or question.
